### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by chpp123** [AlanLi1997/slim-neck-by-gsconv#1]
你好,非常感谢您在YOLOv5模型做出的改进研究,认真拜读了您的文章,受益匪浅,可以麻烦您提供下common.py以及gsconv文章里的实验涉及到的代码么,我想应用在遥感目标检测领域,您觉得可行么,期望收到您的回复,第一个发issues非常荣幸.

**Comment by zimenglan-sysu-512** [comment]
+1

**Comment by AlanLi1997** [comment]
您好，感谢您对我们的工作的关注。由于某些原因，我们不得不放缓关键代码的更新。但我们一定会尽快更新核心代码(大约在7月15日之前)，请您持续关注该仓库。

> 你好,非常感谢您在YOLOv5模型做出的改进研究,认真拜读了您的文章,受益匪浅,可以麻烦您提供下common.py以及gsconv文章里的实验涉及到的代码么,我想应用在遥感目标检测领域,您觉得可行么,期望收到您的回复,第一个发issues非常荣幸.

**Comment by dengbuqi** [comment]
@chpp123 
我简单的复现了一下，不一定正确，但是您可以参考一下。
[https://github.com/dengbuqi/Gsconv
](https://github.com/dengbuqi/Gsconv
)

**Comment by guohaochen** [comment]
> @chpp123 我简单的复现了一下，不一定正确，但是您可以参考一下。 [https://github.com/dengbuqi/Gsconv ](https://github.com/dengbuqi/Gsconv) 我也在期待官方代码的更新！+1 ^_^!

你好，非常感谢你提供的复现代码，简单看了一下，我发现[https://github.com/dengbuqi/Gsconv/blob/main/Gsconv.py]第61-62行的代码是否需要修改一下
        _,C,_,_ = x.shape
        x = channel_shuffle(x, C)
channel_shuffle中将输入x的通道进行打乱，可是分组数是x的通道数，每一组只有1个channel，这岂不是没有起到作用？
是否写成：
        _,C,_,_ = x.shape
        x = channel_shuffle(x, C//2)
从论文的图片3中，我理解的是将Conv生成的特征和DWConv生成的特征进行交叉打乱，所以分组数是通道数的一半，使得两个channel进行一次打乱？
不知道我的想法对不对，可能是我想错了，如果我错了请告诉我，谢谢。

**Comment by AlanLi1997** [comment]
We uploaded the **GSConv** model: [https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/main/models_inPaper.py](url)
And the other models in the paper will also be uploaded soon(before July 15th).
Thank you for your interest in _Slim-neck by GSConv: A better design paradigm of detector architectures for autonomous vehicles_
@chpp123 @zimenglan-sysu-512 @guohaochen @dengbuqi
