### ISSUE TITLE
训练参数设置

### ISSUE THREAD

**Issue by tu12306** [AlanLi1997/slim-neck-by-gsconv#10]
您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？  没有预训练权重？

**Comment by tu12306** [comment]
大概多少epoch呢？

**Comment by AlanLi1997** [comment]
> 您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？ 没有预训练权重？

您好，33000指的是训练的迭代次数。batch size我们设置为128，epoches为600，保存在验证集上的最优结果的权重。我们暂时没有提供预训练权重，但若您需要，我将在后续上传Slim neck by GSConv的基础模型(不附带tricks，比如CoordAttention)在PASCAL VOC和COCO上的预训练权重。

**Comment by tu12306** [comment]
我有一个疑问是您训练超参数是如何设置的呢，我的实验环境在windows下进行的 运行结果和您相差很大。YOLOv5n在Pascal VOC上训练使用的超参数选择了U版的 hyp.scretch-low.yaml ,&nbsp;https://github.com/WongKinYiu/PyTorch_YOLOv4选择的超参数文件我同样使用了U版的 hyp.scretch-low.yaml&nbsp;
请问这样是不是不符合您文中对比实验的设置呢？


我在voc数据集上训练yolov5n时也使用过hyp.VOC.yaml，运行300轮达到45.3mAP0.5，可能按照您说的运行600轮数值会有很大的增加


非常感谢您的耐心解答~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlanLi1997/slim-neck-by-gsconv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlanLi1997/slim-neck-by-gsconv] 训练参数设置 (Issue #10)





  
您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？ 没有预训练权重？
  
您好，33000指的是训练的迭代次数。batch size我们设置为128，epoches为600，保存在验证集上的最优结果的权重。我们暂时没有提供预训练权重，但若您需要，我将在后续上传Slim neck by GSConv的基础模型(不附带tricks，比如CoordAttention)在PASCAL VOC和COCO上的预训练权重。

**Comment by AlanLi1997** [comment]
您好，我们在Linux 上训练的所有模型，使用的超参数是[hyp.scretch-med.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/2ae57d23f50fd65c7c292cfeb01646faf0a0d997/gsconv-yolov5/data/hyps/hyp.scratch-med.yaml)。更多具体的超参数设置您能在论文v2版本第4节找到。如果保持同样的超参数设置，您应该获得和论文中非常相近的结果。这是我们用Tensorboard监控的slimneck-yolov5在PASCAL VOC上的训练过程(bs=128, epoches=800, 但在第600轮时，val-mAP0.5已超过62%，使用了CoordAttention等tricks)，您可以作为参考。
![testv5](https://user-images.githubusercontent.com/80144976/192089017-29b004d6-ea30-4179-a002-b2a26620099b.png)

一个补充，您可以考虑使用[我们分配的数据集](https://github.com/AlanLi1997/slim-neck-by-gsconv/tree/master/datasets/VOC2012)进行训练。

**Comment by AlanLi1997** [comment]
> 我有一个疑问是您训练超参数是如何设置的呢，我的实验环境在windows下进行的 运行结果和您相差很大。YOLOv5n在Pascal VOC上训练使用的超参数选择了U版的 hyp.scretch-low.yaml ,&nbsp;[https://github.com/WongKinYiu/PyTorch_YOLOv4选择的超参数文件我同样使用了U版的](https://github.com/WongKinYiu/PyTorch_YOLOv4%E9%80%89%E6%8B%A9%E7%9A%84%E8%B6%85%E5%8F%82%E6%95%B0%E6%96%87%E4%BB%B6%E6%88%91%E5%90%8C%E6%A0%B7%E4%BD%BF%E7%94%A8%E4%BA%86U%E7%89%88%E7%9A%84) hyp.scretch-low.yaml&nbsp; 请问这样是不是不符合您文中对比实验的设置呢？ 我在voc数据集上训练yolov5n时也使用过hyp.VOC.yaml，运行300轮达到45.3mAP0.5，可能按照您说的运行600轮数值会有很大的增加 非常感谢您的耐心解答~
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AlanLi1997/slim-neck-by-gsconv" ***@***.***&gt;; 发送时间:&nbsp;2022年9月23日(星期五) 中午12:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [AlanLi1997/slim-neck-by-gsconv] 训练参数设置 (Issue #10) 您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？ 没有预训练权重？ 您好，33000指的是训练的迭代次数。batch size我们设置为128，epoches为600，保存在验证集上的最优结果的权重。我们暂时没有提供预训练权重，但若您需要，我将在后续上传Slim neck by GSConv的基础模型(不附带tricks，比如CoordAttention)在PASCAL VOC和COCO上的预训练权重。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，我们在Linux 上训练的所有模型，使用的超参数是[hyp.scretch-med.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/2ae57d23f50fd65c7c292cfeb01646faf0a0d997/gsconv-yolov5/data/hyps/hyp.scratch-med.yaml)。更多具体的超参数设置您能在论文v2版本第4节找到。如果保持同样的超参数设置，您应该获得和论文中非常相近的结果。这是我们用Tensorboard监控的slimneck-yolov5在PASCAL VOC上的训练过程(bs=128, epoches=800, 但在第594轮时，val-mAP0.5已超过62%，使用了CoordAttention等tricks)，您可以作为参考。
![testv5](https://user-images.githubusercontent.com/80144976/192089017-29b004d6-ea30-4179-a002-b2a26620099b.png)

一个补充，您可以考虑使用[我们分配的数据集](https://github.com/AlanLi1997/slim-neck-by-gsconv/tree/master/datasets/VOC2012)进行训练。

**Comment by AlanLi1997** [comment]
> 您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？ 没有预训练权重？

我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)

**Comment by tu12306** [comment]
非常感谢您的答复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月24日(星期一) 晚上7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [AlanLi1997/slim-neck-by-gsconv] 训练参数设置 (Issue #10)





  
您好，请问您文中的step33000是指什么呢 类似yolov5的epoch？ 没有预训练权重？
  
我们现在提供了GS-yolov5n在MS COCO2017的预训练权重
