### ISSUE TITLE
注意力添加在哪个位置？

### ISSUE THREAD

**Issue by wenjunx** [AlanLi1997/slim-neck-by-gsconv#11]
你好，想请教下三个注意力添加在哪几个位置，参考一下

**Comment by wenjunx** [comment]
我看论文建议是放在主干末端，那3*CA是在主干最后放三个CA的意思嘛

**Comment by wenjunx** [comment]
还有那个SPPF*4是在同个位置，同通道数直接用四次的意思吗？可以提供点细节吗？期待您的回复，感谢您的工作，谢谢了！

**Comment by AlanLi1997** [comment]
> 你好，想请教下三个注意力添加在哪几个位置，参考一下

你好，我们上传了一个添加注意力模块的[GSConv-yolov5-attention.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/GSConv-yolov5s-attention.yaml)文件，可以作为您的一个参考。您需要将您希望使用的注意力模添加在我们提供的样例的位置。3*CA和4*SPPF是指使用的CA和SPPF模块的次数，要注意，这些模块不是在同一位置重复使用的。补充的信息参考 #6

**Comment by RainyMoring** [comment]
您好,请问这个4SPPF的4次是分别添加在了哪个地方?是每个特征层的输出部分吗?我在您的https://github.com/AlanLi1997/slim-neck-by-gsconv/issues/6里没有看到详细说明

**Comment by AlanLi1997** [comment]
> 您好,请问这个4SPPF的4次是分别添加在了哪个地方?是每个特征层的输出部分吗?我在您的[https://github.com/AlanLi1997/slim-neck-by-gsconv/issues/6里没有看到详细说明](https://github.com/AlanLi1997/slim-neck-by-gsconv/issues/6%E9%87%8C%E6%B2%A1%E6%9C%89%E7%9C%8B%E5%88%B0%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

你好，backbone最后插入了一个SPP模块，其余三个SPP可以直接插入检测头前，如下：

---
YOLOv5 v6.0 head
head:
  [[-1, 1, GSConv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 8], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 16

   [-1, 1, GSConv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 5], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 20 (P3/8-small)
   [-1, 1. SPPF, [256, 5]], # <---------------

   [-1, 1, GSConv, [256, 3, 2]],
   [[-1, 17], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 23 (P4/16-medium)
   [-1, 1. SPPF, [512, 5]],  # <---------------

   [-1, 1, GSConv, [512, 3, 2]],
   [[-1, 13], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 26 (P5/32-large)
   [-1, 1. SPPF, [1024, 5]],  # <---------------

   [[21, 25, 29], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
