### ISSUE TITLE
GSConv-GhostNet-YOLOv5s模型的配置文件是怎样的？

### ISSUE THREAD

**Issue by River-Cold** [AlanLi1997/slim-neck-by-gsconv#12]
非常感谢您的工作。我看到论文在Table9中提到使用GSConv-GhostNet-YOLOv5s比使用GhostNet-YOLOv5s精度有所提升，但GSConv-GhostNet-YOLOv5s的配置文件并没有在仓库中给出。
![image](https://user-images.githubusercontent.com/80696033/195484054-55696f6a-2dce-487c-a9c4-4873bc742423.png)

我想复现这个结果，但不太清楚这里是以下哪种方案：
1、将GhostNet的neck部分的Conv替换成GSConv，C3Ghost保持不变
https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s1.yaml
2、将GhostNet的neck部分的Conv替换成GSConv，C3Ghost也替换成普通C3
https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s2.yaml
3、将GhostNet的neck部分全部替换为SlimNeck
https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s3.yaml
麻烦您帮忙看一下以上哪一种方式是您在论文中使用的？期待您的指导

**Comment by AlanLi1997** [comment]
> 非常感谢您的工作。我看到论文在Table9中提到使用GSConv-GhostNet-YOLOv5s比使用GhostNet-YOLOv5s精度有所提升，但GSConv-GhostNet-YOLOv5s的配置文件并没有在仓库中给出。 ![image](https://user-images.githubusercontent.com/80696033/195484054-55696f6a-2dce-487c-a9c4-4873bc742423.png)
> 
> 我想复现这个结果，但不太清楚这里是以下哪种方案： 1、将GhostNet的neck部分的Conv替换成GSConv，C3Ghost保持不变 https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s1.yaml 2、将GhostNet的neck部分的Conv替换成GSConv，C3Ghost也替换成普通C3 https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s2.yaml 3、将GhostNet的neck部分全部替换为SlimNeck https://github.com/River-Cold/slim-neck-by-gsconv/blob/master/gsconv-yolov5/models/ghostnet/GSConv-ghost-yolov5s3.yaml 麻烦您帮忙看一下以上哪一种方式是您在论文中使用的？期待您的指导

您好，我们设置Table9中最后一组实验是为了对比GhostConv和GSConv的先进性，因此，您仅需要将整个模型中所有的GhostConv全部替换成GSConv即可，无论是backbone还是neck中(包括C3Ghost中用到的GhostConv)。如果您的模型配置符合以上描述，那么您的模型参数量应该和Table9中报告的参数量一致。在该仓库的VOC2007+12的上，您可以得到这个结果：约61~62%mAP0.5的验证集精度，63~64%mAP0.5的测试集精度。这是我们当初保留的tensorboard监控的训练过程：
![GSConv-Ghost-v5s](https://user-images.githubusercontent.com/80144976/195747278-5fe82b57-c750-4c5d-95c4-90809eaf10bb.jpg)

**Comment by AlanLi1997** [comment]
> 

是的，你只需要找出所有的GhostConv并用GSConv去替换它们🍺
