### ISSUE TITLE
voc数据集评价指标问题

### ISSUE THREAD

**Issue by tinykrystal** [AlanLi1997/slim-neck-by-gsconv#16]
你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复

**Comment by AlanLi1997** [comment]
> 你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复

你好，在我们的实验中，GS-yolov5n在Pascal VOC2007+12数据集上的最好性能是0.64+左右，您的结果(0.7+)明显优于我们的实验，可能是数据集不一致。在该仓库中，我们重新划分了Pascal VOC2007+12的训练集、验证集和测试集，或许您可以用该仓库提供的数据集测试；另一个办法，我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)，验证集的mAP0.5约为0.469-0.470，您可以在MS COCO上测试。

**Comment by tinykrystal** [comment]
您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。

**Comment by tinykrystal** [comment]
您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。

**Comment by tinykrystal** [comment]
您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。

> > 你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复
> 
> 你好，在我们的实验中，GS-yolov5n在Pascal VOC2007+12数据集上的最好性能是0.64+左右，您的结果(0.7+)明显优于我们的实验，可能是数据集不一致。在该仓库中，我们重新划分了Pascal VOC2007+12的训练集、验证集和测试集，或许您可以用该仓库提供的数据集测试；另一个办法，我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)，验证集的mAP0.5约为0.469-0.470，您可以在MS COCO上测试。

**Comment by tinykrystal** [comment]
您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。

> > 你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复
> 
> 你好，在我们的实验中，GS-yolov5n在Pascal VOC2007+12数据集上的最好性能是0.64+左右，您的结果(0.7+)明显优于我们的实验，可能是数据集不一致。在该仓库中，我们重新划分了Pascal VOC2007+12的训练集、验证集和测试集，或许您可以用该仓库提供的数据集测试；另一个办法，我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)，验证集的mAP0.5约为0.469-0.470，您可以在MS COCO上测试。

**Comment by AlanLi1997** [comment]
> 您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。
> 
> > > 你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复
> > 
> > 
> > 你好，在我们的实验中，GS-yolov5n在Pascal VOC2007+12数据集上的最好性能是0.64+左右，您的结果(0.7+)明显优于我们的实验，可能是数据集不一致。在该仓库中，我们重新划分了Pascal VOC2007+12的训练集、验证集和测试集，或许您可以用该仓库提供的数据集测试；另一个办法，我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)，验证集的mAP0.5约为0.469-0.470，您可以在MS COCO上测试。

我们未使用预训练权重。

**Comment by tinykrystal** [comment]
> > 您好，感谢你的回复。我用的是VOC07+12数据集，其中16551张用于训练，4952张用于测试，确实与你的数据集不一样。还有请问训练这些模型的时候有是否使用官方提供的预训练权重。
> > > > 你好！看了文章之后，复现了你的代码，我发现在voc数据集上，yolov5n，包括yolov5n-slim-neck的mAP的值都在0.7+，不知道为什么会差这么多，希望能得到您的回复
> > > 
> > > 
> > > 你好，在我们的实验中，GS-yolov5n在Pascal VOC2007+12数据集上的最好性能是0.64+左右，您的结果(0.7+)明显优于我们的实验，可能是数据集不一致。在该仓库中，我们重新划分了Pascal VOC2007+12的训练集、验证集和测试集，或许您可以用该仓库提供的数据集测试；另一个办法，我们现在提供了[GS-yolov5n在MS COCO2017的预训练权重](https://raw.githubusercontent.com/AlanLi1997/slim-neck-by-gsconv/master/pre_trained_weights/GSyolov5n.pt)，验证集的mAP0.5约为0.469-0.470，您可以在MS COCO上测试。
> 
> 我们未使用预训练权重。

好的，非常感谢！
