### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by taotao6** [AlanLi1997/slim-neck-by-gsconv#17]
![image](https://user-images.githubusercontent.com/37886233/199013051-ebf182ba-9083-4629-b88a-56c5e459aad4.png)

大佬能看看嘛，Python-3.9.7 torch-1.12.1+cu116

**Comment by AlanLi1997** [comment]
> ![image](https://user-images.githubusercontent.com/37886233/199013051-ebf182ba-9083-4629-b88a-56c5e459aad4.png)
> 
> 大佬能看看嘛，Python-3.9.7 torch-1.12.1+cu116

你好。很抱歉，根据已有的信息我无法判断错误发生的原因， 或许你可以根据提供的[requirements](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/requirements.txt)来配置环境#14

**Comment by taotao6** [comment]
> > ![image](https://user-images.githubusercontent.com/37886233/199013051-ebf182ba-9083-4629-b88a-56c5e459aad4.png)
> > 大佬能看看嘛，Python-3.9.7 torch-1.12.1+cu116
> 
> 你好。很抱歉，根据已有的信息我无法判断错误发生的原因， 或许你可以根据提供的[requirements](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/requirements.txt)来配置环境#14

根据那个文件，我看了配置的环境没问题。下面是我的全部报错情况，能看看吗


Traceback (most recent call last):
  File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 374, in <module>
    model = Model(opt.cfg).to(device)
  File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 195, in __init__  
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 194, in <lambda>  
    forward = lambda x: self.forward(x)[0] if isinstance(m, Segment) else self.forward(x)
  File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 209, in forward   
    return self._forward_once(x, profile, visualize)  # single-scale inference, train 
  File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Graduate\Code\yolov5\yolov5-master\models\common.py", line 1829, in forward
    x1 = self.cv1(x)
  File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Graduate\Code\yolov5\yolov5-master\models\common.py", line 58, in forward  
    return self.act(self.bn(self.conv(x)))
  File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 45      didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)

**Comment by AlanLi1997** [comment]
> > > ![image](https://user-images.githubusercontent.com/37886233/199013051-ebf182ba-9083-4629-b88a-56c5e459aad4.png)
> > > 大佬能看看嘛，Python-3.9.7 torch-1.12.1+cu116
> > 
> > 
> > 你好。很抱歉，根据已有的信息我无法判断错误发生的原因， 或许你可以根据提供的[requirements](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/requirements.txt)来配置环境#14
> 
> 根据那个文件，我看了配置的环境没问题。下面是我的全部报错情况，能看看吗
> 
> Traceback (most recent call last): File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 374, in model = Model(opt.cfg).to(device) File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 195, in **init** m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))]) # forward File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 194, in forward = lambda x: self.forward(x)[0] if isinstance(m, Segment) else self.forward(x) File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 209, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "d:\Graduate\Code\yolov5\yolov5-master\models\yolo.py", line 121, in _forward_once x = m(x) # run File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "D:\Graduate\Code\yolov5\yolov5-master\models\common.py", line 1829, in forward x1 = self.cv1(x) File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "D:\Graduate\Code\yolov5\yolov5-master\models\common.py", line 58, in forward return self.act(self.bn(self.conv(x))) File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "D:\Users\taotao\anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 45 didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)
> 
> * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
>   didn't match because some of the arguments have invalid types: (Tensor, Parameter, NoneType, tuple, tuple, tuple, int)

你好，我们提供的仓库中的common.py并没有line 1829, 所以，我认为您遇到的错误不是我们提供的代码中发生的，您或许可以尝试克隆我们仓库的代码运行测试。
