### ISSUE TITLE
对于yolox这种anchor free也是有效的吗

### ISSUE THREAD

**Issue by mcmingchang** [AlanLi1997/slim-neck-by-gsconv#2]

**Comment by AlanLi1997** [comment]
@mcmingchang 我认为是的。如果您希望减少CNNs模型的参数量和计算复杂度但保留精度，slim neck by gsconv方法将是一个好的选择。我们将于7月15日前更新gsconv和VoV-GSCSP代码，您可以进行相关实验验证并公布结果。

**Comment by mcmingchang** [comment]
我看你用的激活函数是mish，用silu的话会不会速度和准确率还能再提升呢？

**Comment by mcmingchang** [comment]
能快点开源就好啦，哈哈哈，用在yolov7会不会冲突呀

**Comment by mcmingchang** [comment]
我把网络写到yolox上了，但是发现比原版慢，batchsize=10的情况下，新版是0.01494 s ， 原版是time cost: 0.01323 s
这个是我的github项目地址  https://github.com/mcmingchang/yolox_keypoint_segment
你直接查看123.py运行即可。
是我写错了吗，还是说对anchor free作用不大？

**Comment by AlanLi1997** [comment]
> 我把网络写到yolox上了，但是发现比原版慢，batchsize=10的情况下，新版是0.01494 s ， 原版是time cost: 0.01323 s 这个是我的github项目地址 https://github.com/mcmingchang/yolox_keypoint_segment 你直接查看123.py运行即可。 是我写错了吗，还是说对anchor free作用不大？

这主要取决于您的硬件，例如yolov5的focus在不同硬件上的速度表现。也许您可以在这里找到一些答案[Roofline]https://escholarship.org/uc/item/5tz795vq)

**Comment by mcmingchang** [comment]
ok，还有就是这个网络训练起来明显比原版s慢不少，好像也不怎么收敛的样子

**Comment by AlanLi1997** [comment]
> ok，还有就是这个网络训练起来明显比原版s慢不少，好像也不怎么收敛的样子

感谢您的反馈。请您告诉我们您实验的数据集，以便于我们测试和优化基于GSConv的一次性聚合CSP结构🚀

**Comment by mcmingchang** [comment]
在batch=10的情况下，原始模型耗时0.01857 s，新模型耗时0.01692 s，推理输入大小为10,3,192,320。模型能收敛，只是比较慢。训练耗时的话旧模型跑完300epoch需要10小时，新模型需要32小时，原因不明

**Comment by mcmingchang** [comment]
导出成trt的时候GSConv报错。y.permute(1, 0, 2)，第一个必须是0，也就是batch的位置不能动

**Comment by AlanLi1997** [comment]
> 导出成trt的时候GSConv报错。y.permute(1, 0, 2)，第一个必须是0，也就是batch的位置不能动

这是因为shuffle操作不是一种“规范”的操作方式，在某种意义上来说，类似于Focus结构(from Yolov5)。我们正在尝试采用“规范”的方式来完成shuffle。相关实验正在进行，我们会尽快(大约1个月内)更新下个版本的GSConv，采用了“规范化”的shuffle操作。🚀
如果您认为这个issue得到了解决，请关闭它。🍻

**Comment by mcmingchang** [comment]
有更新可以通知一下吗，谢谢

**Comment by AlanLi1997** [comment]
> 有更新可以通知一下吗，谢谢

Hi, 我们暂时通过最简单的线性计算完成shuffle操作(不需要BN层和激活)，这是规范的算子，支持TRT加速[GSConv1](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/main/models_inPaper.py)。
在VOC2007+12上，使用GSConv1的yolov5n推理速度比使用GSConv的慢0.2ms，AP0.5低0.3%。

**Comment by xiyang1012** [comment]
shuffle操作和ShuffleNet的channel_shuffle是一样的吗，是否可以参考这个实现，batch固定 [ShuffleNet](https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe/blob/master/slim.py#L24)

**Comment by mcmingchang** [comment]
新版结构是可以转trt了，但是跟yolox官方原版结构的trt，batch=10速度好像差不多，准确率还没测
