### ISSUE TITLE
请问仓库中的示例航拍图片是640x640训练出来的吗？不会吧？

### ISSUE THREAD

**Issue by FlyingAnt2018** [AlanLi1997/slim-neck-by-gsconv#20]

**Comment by AlanLi1997** [comment]
你好，示例遥感图像检测的细节:
训练-DOTA1.0数据集(图像分割后分辨率约1080×960)，训练分辨率缩放为640×640；
测试示例-ITCVD数据集，推理分辨率1280×1280.

**Comment by AlanLi1997** [comment]
你好，示例遥感图像检测的细节:
训练-DOTA1.0数据集(图像分割后分辨率约1080×960)，训练分辨率缩放为640×640；
测试示例-ITCVD数据集，推理分辨率1280×1280.

**Comment by FlyingAnt2018** [comment]
了解，谢谢。
测试“测试示例-ITCVD数据集”模型方便开放吗？

**Comment by AlanLi1997** [comment]
> 了解，谢谢。 测试“测试示例-ITCVD数据集”模型方便开放吗？

当然，我尽快回去找到这两个训练权重然后上传🍻

**Comment by FlyingAnt2018** [comment]
🤙🤙🤙



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月02日 23:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AlanLi1997/slim-neck-by-gsconv] 请问仓库中的示例航拍图片是640x640训练出来的吗？不会吧？ (Issue #20) |

了解，谢谢。 测试“测试示例-ITCVD数据集”模型方便开放吗？

当然，我尽快回去找到这两个训练权重然后上传🍻

**Comment by AlanLi1997** [comment]
> 了解，谢谢。 测试“测试示例-ITCVD数据集”模型方便开放吗？

你好，论文中测试ITCVD遥感数据集所用权重已上传[GS-saled-v4-DOTA1.0](https://github.com/AlanLi1997/slim-neck-by-gsconv/raw/master/pre_trained_weights/GS-scaled-v4-DOTA1.pt)，复现可参考[DOTA1.0.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/datasets/DOTA1.0.yaml)

**Comment by FlyingAnt2018** [comment]
你好，我发现两个问题。
1. 文章中说的测试图片是测试机第23帧，其实应该是训练集第23张图片。
2. 所给模型在用所给仓库代码解析的时候，报错：AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/code/slim-neck-by-gsconv/gsconv-scaled-yolov4/models/common.py'>。

**Comment by AlanLi1997** [comment]
> 你好，我发现两个问题。
> 
> 1. 文章中说的测试图片是测试机第23帧，其实应该是训练集第23张图片。
> 2. 所给模型在用所给仓库代码解析的时候，报错：AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/code/slim-neck-by-gsconv/gsconv-scaled-yolov4/models/common.py'>。

你好，
1. 我们使用DOTA1.0数据集进行训练使用ITCVD数据集进行测试，而并未使用ITCVD数据集进行训练，因此，您指的“应该是训练集第23张图片”并不会对测试结果公平性造成任何影响.
2. SPPF即Yolov5中所使用的SPPF模块.

**Comment by FlyingAnt2018** [comment]
> 

您说的对。我想说的是，没有模型结构yaml文件的话，拿到权重也没办法复现检测结果。文章中提到的 slim-neck scaled YOLOv4l. 意思是在scaled-yolov4 large的基础上，普通卷积替换为GSC卷积，SPPCSP替换为SPPF嘛？

**Comment by AlanLi1997** [comment]
> > 
> 
> 您说的对。我想说的是，没有模型结构yaml文件的话，拿到权重也没办法复现检测结果。文章中提到的 slim-neck scaled YOLOv4l. 意思是在scaled-yolov4 large的基础上，普通卷积替换为GSC卷积，SPPCSP替换为SPPF嘛？

你好，感谢提醒，仓库中包含了yaml文件[SN-yolov4-p5.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/gsconv-scaled-yolov4/models/SN-yolov4-p5.yaml)
为了简化结构，我们当时似乎确实用SPPF替代了SPPCSP，而仓库中的yaml文件保留了SPPCSP(line 33)，您可自行选择，但结果应该不会有较大差异。
