### ISSUE TITLE
请问GSConv中的G和S分别是什么意思

### ISSUE THREAD

**Issue by zhijiandev** [AlanLi1997/slim-neck-by-gsconv#22]

**Comment by AlanLi1997** [comment]
你好，GSConv是一种**标准卷积+深度卷积**的轻量级卷积方法，[表现为GroupConv+shuffle 或 GhostConv+shuffle](https://github.com/AlanLi1997/slim-neck-by-gsconv/issues/21#issuecomment-1465447646)
