### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by icehumian** [AlanLi1997/slim-neck-by-gsconv#23]
Hello！When I use the module VoVGSCSPC，this error will be generated
Traceback (most recent call last):
  File "D:\my_yolov5\models\yolo.py", line 386, in <module>
    model = Model(opt.cfg).to(device)
  File "D:\my_yolov5\models\yolo.py", line 197, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "D:\my_yolov5\models\yolo.py", line 358, in parse_model
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
  File "D:\my_yolov5\models\common.py", line 182, in __init__
    super().__init__(c1, c2, e)
  File "D:\my_yolov5\models\common.py", line 169, in __init__
    self.gsb = nn.Sequential(*(GSBottleneck(c_, c_, e=1.0) for _ in range(n)))
TypeError: 'float' object cannot be interpreted as an integer

**Comment by AlanLi1997** [comment]
> Hello！When I use the module VoVGSCSPC，this error will be generated Traceback (most recent call last): File "D:\my_yolov5\models\yolo.py", line 386, in model = Model(opt.cfg).to(device) File "D:\my_yolov5\models\yolo.py", line 197, in **init** self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch]) # model, savelist File "D:\my_yolov5\models\yolo.py", line 358, in parse_model m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(_args) # module File "D:\my_yolov5\models\common.py", line 182, in **init** super().**init**(c1, c2, e) File "D:\my_yolov5\models\common.py", line 169, in **init** self.gsb = nn.Sequential(_(GSBottleneck(c_, c_, e=1.0) for _ in range(n))) TypeError: 'float' object cannot be interpreted as an integer

Thanks for the feedback, it has been fixed! Re-cloning and runing ✔
