### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by Amuleter** [AlanLi1997/slim-neck-by-gsconv#28]
I faced error: result type Float can't be cast to the desired output type long int when train

solved by edit loss.py as below:
https://github.com/ultralytics/yolov5/pull/8067/files

**Comment by AlanLi1997** [comment]
> I faced error: result type Float can't be cast to the desired output type long int when train
> 
> solved by edit loss.py as below: https://github.com/ultralytics/yolov5/pull/8067/files

Thanks for your feedback and I will fix this soon.
