### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by buyuxixi** [AlanLi1997/slim-neck-by-gsconv#29]
b, n, h, w = x2.data.size()
        b_n = b * n // 2
        y = x2.reshape(b_n, 2, h * w)
        y = y.permute(1, 0, 2)
        y = y.reshape(2, -1, n // 2, h, w)

        return torch.cat((y[0], y[1]), 1)

这段代码中的b,n是什么意思

**Comment by AlanLi1997** [comment]
> ```
>     b, n, h, w = x2.data.size()
>     b_n = b * n // 2
>     y = x2.reshape(b_n, 2, h * w)
>     y = y.permute(1, 0, 2)
>     y = y.reshape(2, -1, n // 2, h, w)
> 
>     return torch.cat((y[0], y[1]), 1)
> ```
> 
> 这段代码中的b,n是什么意思

batch size & number of channels
