### ISSUE TITLE
主干部分应用GSconv会有多大的收益呢？

### ISSUE THREAD

**Issue by moxigk** [AlanLi1997/slim-neck-by-gsconv#3]
只在主干部分使用GSconv，会不会有很小的提升呢？

**Comment by AlanLi1997** [comment]
> 只在主干部分使用GSconv，会不会有很小的提升呢？

答案取决于您的使用场景：使用GSConv去替换使用普通卷积层搭建的backbone，模型精度会下降(因为参数量和FLOPs降低了接近50%)；使用GSConv去替换轻量级的backbone如Ghostnet等，模型精度会提高且参数量与FLOPs不变🍻
