### ISSUE TITLE
数据集的标注文件

### ISSUE THREAD

**Issue by hwrhwr** [AlanLi1997/slim-neck-by-gsconv#30]
请问还能提供一下SODA10M数据集的标注文件吗？谢谢！！！！！！！！！！

**Comment by AlanLi1997** [comment]
> 请问还能提供一下SODA10M数据集的标注文件吗？谢谢！！！！！！！！！！

更新误删，已重新上传至(仓库)[https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/datasets/SODA10M/SODA10M_2Ddet_labels.zip]

**Comment by AlanLi1997** [comment]
更新误删，已重新上传至[仓库](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/datasets/SODA10M/SODA10M_2Ddet_labels.zip)

**Comment by AlanLi1997** [comment]
已重传至仓库，[下载](blob:https://github.com/74e2541e-5e96-4a37-8885-6bc4b4d0b468)

**Comment by AlanLi1997** [comment]
已重新上传至[仓库](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/datasets/SODA10M/SODA10M_2Ddet_labels.zip)

**Comment by hwrhwr** [comment]
> 已重新上传至[仓库](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/master/datasets/SODA10M/SODA10M_2Ddet_labels.zip)

谢谢！！！！！！
