### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by polaris74** [AlanLi1997/slim-neck-by-gsconv#4]
请问出现这个问题怎么办呢

**Comment by dengbuqi** [comment]
你检查一下你对应错误的行，是不是有什么地方除数设置成0了

**Comment by polaris74** [comment]
> 

我是把这个common里的模块放到yolov5官方代码的common里然后把yolov5s.yaml文件改了，别的地方没有改动。

**Comment by dengbuqi** [comment]
> > 
> 
> 我是把这个common里的模块放到yolov5官方代码的common里然后把yolov5s.yaml文件改了，别的地方没有改动。

你先按我说的Debug看看

**Comment by AlanLi1997** [comment]
请将您修改的代码的部分完整地展示出来，以便于定位错误并修复🍻

**Comment by polaris74** [comment]
我了解了，是因为我在yolo.py里忘记加入这几个模块了，同时请问一下这个能适配在yolov7吗

**Comment by AlanLi1997** [comment]
> 我了解了，是因为我在yolo.py里忘记加入这几个模块了，同时请问一下这个能适配在yolov7吗

我认为是的，GSConv是一个通用的(在部分特殊硬件上可能不被支持)轻量化卷积方式🍻
