### ISSUE TITLE
map问题

### ISSUE THREAD

**Issue by qiao-xu** [AlanLi1997/slim-neck-by-gsconv#5]
请问您使用的soda10m数据集，包含了几个类别？使用GSConv的yolov5s在该数据集上的map大概能达到多少，我在soda10m上进行训练，精度有些降低，但计算量少了很多。

**Comment by AlanLi1997** [comment]
> 请问您使用的soda10m数据集，包含了几个类别？使用GSConv的yolov5s在该数据集上的map大概能达到多少，我在soda10m上进行训练，精度有些降低，但计算量少了很多。

我们上传了[SODA10M.yaml](https://github.com/AlanLi1997/slim-neck-by-gsconv/blob/main/datasets/SODA10M/SODA10M.yaml)文件，您可以在里面找到类别数。我们在论文中报告了mAP。另外，若您希望获得精度提高，别忘了使用free tricks🍻
