### ISSUE TITLE
注意力机制

### ISSUE THREAD

**Issue by werf158297** [AlanLi1997/slim-neck-by-gsconv#6]
您好,请问文章中提到的几种加入注意力机制和SPPF的改动是在网络哪些部分呢？

**Comment by AlanLi1997** [comment]
> 您好,请问文章中提到的几种加入注意力机制和SPPF的改动是在网络哪些部分呢？

Hi, 我们在主干部分加入attention模块。细节位置是，在特征图维度发生转移后与进入下一个卷积/瓶颈块之前。我们在论文中解释了相关原因(使用卷积完成下采样时，宽高维度聚合而通道维度扩张，此时使用attention重新分配权值将效益最大化)。🍻
