### ISSUE TITLE
论文里的VoV GSCSP图画错了吧？

### ISSUE THREAD

**Issue by mepleleo** [AlanLi1997/slim-neck-by-gsconv#7]

**Comment by mepleleo** [comment]
还有一个问题，
class GSBottleneck(nn.Module):
    # GS Bottleneck https://github.com/AlanLi1997/slim-neck-by-gsconv
    def __init__(self, c1, c2, k=3, s=1):
        super().__init__()
        c_ = c2 // 2
        # for lighting
        self.conv_lighting = nn.Sequential(
            GSConv(c1, c_, 1, 1),
            GSConv(c_, c2, 1, 1, act=False))
        # for receptive field
        self.conv = nn.Sequential(
            GSConv(c1, c_, 3, 1),
            GSConv(c_, c2, 3, 1, act=False))
        self.shortcut = nn.Identity()

    def forward(self, x):
        return self.conv_lighting(x)
这里面的self.conv 3×3卷积没用到啊？最终用的是self.conv_lighting 1×1的卷积核吗？

**Comment by AlanLi1997** [comment]
> 还有一个问题， class GSBottleneck(nn.Module): # GS Bottleneck https://github.com/AlanLi1997/slim-neck-by-gsconv def **init**(self, c1, c2, k=3, s=1): super().**init**() c_ = c2 // 2 # for lighting self.conv_lighting = nn.Sequential( GSConv(c1, c_, 1, 1), GSConv(c_, c2, 1, 1, act=False)) # for receptive field self.conv = nn.Sequential( GSConv(c1, c_, 3, 1), GSConv(c_, c2, 3, 1, act=False)) self.shortcut = nn.Identity()
> 
> ```
> def forward(self, x):
>     return self.conv_lighting(x)
> ```
> 
> 这里面的self.conv 3×3卷积没用到啊？最终用的是self.conv_lighting 1×1的卷积核吗？

您好，感谢您的提问。arxiv中v1版本论文的VoV-GSCSP结构图是最开始使用的，在当时没有错误，但后面我们进行了代码更新(跳跃连接上嵌入一次卷积操作)，而我们还没有更新论文。arxiv上面的v1版本论文是非正式的初稿，我们还在更新某些结构和进行一些实验，在v2版本论文发布前，您可以关注该仓库的更新；这里的GSBottleneck当前确实用的1*1 卷积。但1*1卷积无法扩大卷积网络的感受野，3*3卷积可以。我们想提供多种选择让这些模型更灵活以适应不同部署场景，而暂时不必和论文保持严格一致。
