### ISSUE TITLE
准确率

### ISSUE THREAD

**Issue by bzha5848** [AlanLi1997/slim-neck-by-gsconv#8]
你好！
我想问一下有没有关于slim-neck再yolov5 上做的关于准确率的实验以及结果啊？
谢谢！！

**Comment by AlanLi1997** [comment]
你好，[论文(v2版本)](https://arxiv.org/abs/2206.02424)中，表9和图7分别详细地报告了slim-neck-yolov5检测器在PASCAL VOC2007+12和SODA10M数据集上的性能。🍻
